routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\PostController;
use App\Http\Controllers\Admin\PostController as AdminPostController;
use App\Http\Controllers\FastPostController;
use App\Http\Controllers\MainPagesAjaxController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\Contact\ContactController;
use App\Http\Controllers\Admin\TagController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Upload\UploadFilesController;
use App\Http\Controllers\Admin\UserController;

// Auth::routes();
Auth::routes(['register' => false]);
//Route::get('/login', ['as' => 'login', 'uses' => 'Auth\LoginController@showLoginForm']);
//Route::post('/login', ['as' => 'login', 'uses' => 'Auth\LoginController@login']);
//Route::post('/logout', ['as' => 'logout', 'uses' => 'Auth\LoginController@logout']);
//Route::get('password/reset', 'Auth\ResetPasswordController@showResetForm')->name('password.request');
//===============================================================================================
Route::get('/blog', [PostController::class, 'index'])->name('blog');
Route::get('/blog/category/{slug}', [PostController::class, 'postsByCategory'])->name('blogCategory');
Route::get('/blog/tag/{slug}', [PostController::class, 'postsByTag'])->name('blogTag');
Route::get('blog/{slug}', [PostController::class, 'singlePost'])->name('blog.single');

Route::get('fastpost', [FastPostController::class, 'index'])->name('FastPost');
Route::get('fastpost/{slug}', [FastPostController::class, 'singleFastPost'])->name('fastPostSingle');
Route::get('/fastpost/tag/{slug}', [FastPostController::class, 'fastPostsByTag'])->name('FastPostTag');
//===============================================================================================
Route::get('comment/getpostcomments/{postId}/{parentId?}/{offset?}', [CommentController::class, 'getPostComments'])->name('comment.getpostcomments');
Route::resource('comment', CommentController::class)->only('store');
Route::resource('contact', ContactController::class)->only(['index', 'store']);
//===============================================================================================
//===============================================================================================
Route::group(['middleware' => ['role:ROLE_REDACTOR']], function () {
    Route::resource('/admin/post', AdminPostController::class)->only('create', 'store', 'index', 'show', 'edit', 'update', 'destroy');
    Route::resource('/admin/upload-files/get', UploadFilesController::class);
});
//===============================================================================================
Route::group(['middleware' => ['role:ROLE_ADMIN']], function () {
    Route::resource('/admin/categories', CategoryController::class)->only(['index', 'edit', 'update', 'create', 'store']);
    Route::resource('/admin/comment',  CommentController::class)->only(['edit', 'update']);
    Route::resource('/admin/tags', TagController::class)->only(['index', 'edit', 'update', 'create', 'store']);
});
//===============================================================================================
Route::group(['middleware' => ['role:ROLE_SUPER_ADMIN']], function () {
    Route::resource('/admin/categories', CategoryController::class)->only(['destroy']);
    Route::resource('/admin/comment', CommentController::class)->only('destroy');
    Route::resource('/admin/tags', TagController::class)->only(['destroy']);
    Route::resource('/admin/user', UserController::class)->only(['create', 'store', 'index', 'show', 'edit', 'update', 'destroy']);
});
//Route::resource('/adminfastpost', 'Admin\FastPostController', ['as' => 'fastpost','only' => ['index','edit', 'update','create','store','show']]);
Route::get('/', [MainPagesAjaxController::class, 'index'])->name('home');
Route::get('/{any}', [MainPagesAjaxController::class, 'index'])->name('pages')->where('any', '.*');

resources/views/adminMenu.blade.php
<article class="container-fluid" style="background: white;padding: 15px">
    <a class="btn btn-success" href="{{route('post.index')}}">Wszystkie posty</a>
    <a class="btn btn-success" href="{{route('post.create')}}">Dodawanie posta</a>
    <a class="btn btn-success" href="{{route('tags.index')}}">Tagi</a>
    <a class="btn btn-success" href="{{route('categories.index')}}">Kategorie</a>
    <a class="btn btn-success" href="{{route('user.index')}}">Użytkownicy</a>
</article>

resources/views/footer.blade.php
<footer class="container-fluid footer text-center" id="footer">
    <div class=container>
        <div class="col-lg-12 wow zoomInUp" data-wow-delay=0.2s>
            <figure><img src="{{ asset('img/svg/laptop.svg') }}" alt="Ikona laptopa" class=svg-footer></figure>
        </div>
        <div class="col-lg-12 pd-zero">
            <a href="https://www.facebook.com/sharer/sharer.php?u={{route('home')}}" class="icon-link jeden wow rotateIn"
               data-wow-delay=1s>
                <i class="fab fa-facebook-f fa-facebook circle-icon" aria-hidden=true></i>
            </a>
            <a class="icon-link wow rotateIn" data-wow-delay=1s href="https://twitter.com/home?status={{route('home')}}">
                <i class="fab fa-twitter circle-icon" aria-hidden=true></i>
            </a>
            <a class="icon-link wow rotateIn" data-wow-delay=1s href="{{route('home')}}">
                <i class="fab fa-instagram circle-icon" aria-hidden=true></i>
            </a>
            <a class="icon-link wow rotateIn" data-wow-delay=1s href="https://plus.google.com/share?url={{route('home')}}">
                <i class="fab fa-google-plus-g fa-google-plus circle-icon" aria-hidden=true></i>
            </a>
        </div>
        <div class="col-lg-12 white-font-09">
            <h3>COPYRIGHT INSTRMNT LIMITED 2021</h3>
            <h5>Powered by <a href="https://pl.wikipedia.org/wiki/AJAX">AJAX!</a></h5>
        </div>
    </div>
</footer>

resources/views/header.blade.php
<header class="header">
    <nav id="nav" class="text-center pd-zero nav-custom no-ajax-load" role="navigation">
        <div class="menu-opener">
            <div class="menu-opener-inner"></div>
        </div>
        <div class="container clearfix" id="myScrollspy">
            <div class="text-menu">
                <figure><img src="{{ asset('img/svg/responsive.svg') }}" alt="Tablet i telefon"></figure>
            </div>
            <ul class="nav">
                <li><a class="page-scroll ajax" href="{{ route('pages', ['']) }}">Home</a></li>
                <li><a class="page-scroll ajax" href="{{ route('pages', ['o-mnie']) }}">O MNIE</a></li>
                {{--<li class="dropdown"> <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Serwis <span class="caret"></span></a>--}}
                    {{--<ul class="dropdown-menu">--}}
                        {{--<li><a href="">Komutery i laptopy</a></li>--}}
                        {{--<li><a href="">Telefony</a></li>--}}
                    {{--</ul>--}}
                {{--</li>--}}
                <li class="dropdown"> <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Portfolio <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a class="ajax" href="{{ route('pages', ['portfolio']) }}">Szablony stron</a></li>
                    </ul>
                </li>
                <li><a class="page-scroll ajax" href="{{route('blog')}}">Blog</a></li>
                <li><a class="page-scroll ajax" href="{{route('FastPost')}}">Szybkie posty</a></li>
                <li><a class="page-scroll ajax" href="{{ route('contact.index') }}">Kontakt</a></li>
                <li><a class="page-scroll" href="{{route('post.create')}}">a</a></li>
                @guest
                @else
                    <li><a class="page-scroll" href="{{route('logout')}}" onclick="event.preventDefault();document.getElementById('logout-form').submit();">Wyloguj</a></li>
                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">@csrf</form>
                @endguest
                <li class="mp3-li">
                    <div class="mp3-container">
                        <div class="change" title="pause/play">
                            <div class="btn-mp3"><span class="eq eq--off" id="link_id"> <span class="eq__bar eq__1"></span><span class="eq__bar eq__2"></span><span class="eq__bar eq__3"></span><span class="eq__bar eq__4"></span><span class="eq__bar eq__5"></span> </span></div>    
                        </div>
                        <div class="mp3-list-container">
                            <div class="text-center control-container">
                                <div class="col-xs-2 control-icon" id="mp3-prev" title="Poprzedni">
                                    <i class="fas fa-step-backward"></i>
                                </div>   
                                <div class="col-xs-2 control-icon" id="mp3-rand" title="Losowe mp3">
                                    <i class="fa fa-random" aria-hidden="true"></i>
                                </div>                
                                <div class="col-xs-2 control-icon" id="mp3-next" title="Następny">
                                    <i class="fas fa-step-forward"></i>
                                </div>           
                                <div class="col-xs-2 control-icon" id="mp3-volume-plus" title="Głośniej">
                                    <i class="fas fa-plus-circle"></i>
                                </div>
                                <div class="col-xs-2 control-icon" id="mp3-volume-minus" title="Ciszej">
                                    <i class="fas fa-minus-circle"></i>
                                </div>    
                                <div class="col-xs-2 control-icon" id="volume-info" title="Poziom głośności od 0-1">1</div> 
                            </div>  
                            <div class="clearfix"></div>
                            <div class="mp3-list"></div>  
                            <div class="clearfix"></div>
                            <div class="text-center">
                                <div id="mp3-time-info" class="mp3-time-info"></div>
                            </div>
                        </div>   
                    </div>
                </li>
                <audio id="mp3Audio"></audio>
            </ul>
        </div>
    </nav>
</header>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/titlePage.blade.php
<article class="container-fluid pd-tp-bt-0">
    <div class="row ligh-bg blog">
        <div class="col-lg-12 white-font text-center">
            <h1>@yield('title')</h1>
            @if (Auth::check() && isset($post))
            <br>
            <div class="row text-center">
                <a class="sendmessage_button" target="_blank"  href="{{ route('post.edit', $post->id) }}">edytuj</a>
            </div>
            @endif
        </div>
    </div>
</article>