routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\PostController;
use App\Http\Controllers\Admin\PostController as AdminPostController;
use App\Http\Controllers\FastPostController;
use App\Http\Controllers\MainPagesAjaxController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\Contact\ContactController;
use App\Http\Controllers\Admin\TagController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Upload\UploadFilesController;
use App\Http\Controllers\Admin\UserController;

// Auth::routes();
Auth::routes(['register' => false]);
//Route::get('/login', ['as' => 'login', 'uses' => 'Auth\LoginController@showLoginForm']);
//Route::post('/login', ['as' => 'login', 'uses' => 'Auth\LoginController@login']);
//Route::post('/logout', ['as' => 'logout', 'uses' => 'Auth\LoginController@logout']);
//Route::get('password/reset', 'Auth\ResetPasswordController@showResetForm')->name('password.request');
//===============================================================================================
Route::get('/blog', [PostController::class, 'index'])->name('blog');
Route::get('/blog/category/{slug}', [PostController::class, 'postsByCategory'])->name('blogCategory');
Route::get('/blog/tag/{slug}', [PostController::class, 'postsByTag'])->name('blogTag');
Route::get('blog/{slug}', [PostController::class, 'singlePost'])->name('blog.single');

Route::get('fastpost', [FastPostController::class, 'index'])->name('FastPost');
Route::get('fastpost/{slug}', [FastPostController::class, 'singleFastPost'])->name('fastPostSingle');
Route::get('/fastpost/tag/{slug}', [FastPostController::class, 'fastPostsByTag'])->name('FastPostTag');
//===============================================================================================
Route::get('comment/getpostcomments/{postId}/{parentId?}/{offset?}', [CommentController::class, 'getPostComments'])->name('comment.getpostcomments');
Route::resource('comment', CommentController::class)->only('store');
Route::resource('contact', ContactController::class)->only(['index', 'store']);
//===============================================================================================
//===============================================================================================
Route::group(['middleware' => ['role:ROLE_REDACTOR']], function () {
    Route::resource('/admin/post', AdminPostController::class)->only('create', 'store', 'index', 'show', 'edit', 'update', 'destroy');
    Route::resource('/admin/upload-files/get', UploadFilesController::class);
});
//===============================================================================================
Route::group(['middleware' => ['role:ROLE_ADMIN']], function () {
    Route::resource('/admin/categories', CategoryController::class)->only(['index', 'edit', 'update', 'create', 'store']);
    Route::resource('/admin/comment',  CommentController::class)->only(['edit', 'update']);
    Route::resource('/admin/tags', TagController::class)->only(['index', 'edit', 'update', 'create', 'store']);
});
//===============================================================================================
Route::group(['middleware' => ['role:ROLE_SUPER_ADMIN']], function () {
    Route::resource('/admin/categories', CategoryController::class)->only(['destroy']);
    Route::resource('/admin/comment', CommentController::class)->only('destroy');
    Route::resource('/admin/tags', TagController::class)->only(['destroy']);
    Route::resource('/admin/user', UserController::class)->only(['create', 'store', 'index', 'show', 'edit', 'update', 'destroy']);
});
//Route::resource('/adminfastpost', 'Admin\FastPostController', ['as' => 'fastpost','only' => ['index','edit', 'update','create','store','show']]);
Route::get('/', [MainPagesAjaxController::class, 'index'])->name('home');
Route::get('/{any}', [MainPagesAjaxController::class, 'index'])->name('pages')->where('any', '.*');

app/Http/Controllers/Admin/PostController.php
<?php

declare(strict_types=1);

namespace App\Http\Controllers\Admin;

use App\Http\Model\Category;
use App\Http\Controllers\Controller;
use App\Http\Repository\PostRepository;
use App\Http\Requests\PostRequest;
use App\Http\Model\Post;
use App\Http\Model\Tag;
use Illuminate\Support\Facades\Auth;
use App\Domain\User\UserRoles;
use App\Domain\Pages\PageTypes;
use App\Domain\Post\Content\BladeToHtmlGenerator;
use Illuminate\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;

class PostController extends Controller
{
    public function __construct()
    {
        $this->middleware('post_permission', ['except' => ['index', 'store', 'show', 'create']]);
    }

    /**
     * @return View|JsonResponse
     */
    public function index(Request $request)
    {
        if (UserRoles::checkRole(UserRoles::ROLE_SUPER_ADMIN, Auth::user()->roles)) {
            $posts = Post::orderBy('id', 'desc');
        } else {
            $posts = Post::where('user_id', '=', Auth::id())->orderBy('id', 'desc');
        }

        if ($request->type) {
            $posts->where('type', '=', $request->type);
        }

        if ($request->title) {
            $posts->where('title', 'LIKE', "%$request->title%");
        }

        $posts = $posts->with('author')->paginate(100);

        $title = 'Wszystkie posty';
        $description = 'Lista postów';

        $pageType = PageTypes::getTypes();

        if ($request->ajax()) {
            return response()->json([
                'content' => view('admin.post.index.indexAjax', compact('posts', 'pageType'))->render(),
                'title' => $title,
                'description' => $description
            ])->header("Vary", "Accept");
        }

        return view('admin.post.index.index', compact('posts', 'title', 'description', 'pageType'));
    }

    public function store(PostRequest $request, PostRepository $postRepository): RedirectResponse
    {
        $postRepository->createPost($request);

        return redirect()->route('post.index')->with('message', 'Dodałem post');
    }

    public function create(): View
    {
        return view('admin.post.create', [
            'categories' => Category::select('id', 'name')->orderBy('name', 'asc')->get(),
            'tags' => Tag::select('id', 'name')->orderBy('name', 'asc')->get(),
            'types' => PageTypes::getTypes()
        ]);
    }

    public function edit(Post $post): View
    {
        return view('admin.post.edit', [
            'post' => $post,
            'categories' => Category::select('id', 'name')->orderBy('name', 'asc')->get(),
            'tags' => Tag::select('id', 'name')->orderBy('name', 'asc')->get(),
            'selectTags' => $post->tags->pluck('id')->all(),
            'selectCategories' => $post->categories->pluck('id')->all(),
            'types' => PageTypes::getTypes(),
        ]);
    }

    public function update(PostRequest $request, Post $post, PostRepository $postRepository): RedirectResponse
    {
        $postRepository->update($post, $request);

        return redirect()->route('post.index')->with('message', 'Zapisałem zmiany');
    }

    public function show(Post $post): View
    {
        $post->content = BladeToHtmlGenerator::generate($post->content);

        return view('admin.post.show', [
            'post' => $post
        ]);
    }

    public function destroy(Post $post, PostRepository $postRepository): RedirectResponse
    {
        $postRepository->delete($post);

        return redirect()->route('post.index')->with('message', 'Post został usuniety');
    }
}

app/Http/Controllers/PostController.php
<?php

declare(strict_types=1);

namespace App\Http\Controllers;

use App\Http\Model\Category;
use App\Http\Repository\PostRepository;
use App\Http\Model\Post;
use App\Http\Repository\CommentRepository;
use App\Domain\Pages\PageTypes;
use App\Domain\Response\Response;
use Illuminate\Http\Request;
use App\Http\Repository\Post\TagRepository;
use Illuminate\Config\Repository;

class PostController extends Controller
{
    private string $title;

    private string $description;

    private int $paginate;

    private Response $response;

    public function __construct(Response $response, Repository $repository)
    {
        $this->response = $response;
        $this->paginate = $repository->get('app.BLOG_CONFIG.BLOG_PAGINATE');
        $this->title = $repository->get('app.BLOG_CONFIG.BLOG_TITLE');
        $this->description = $repository->get('app.BLOG_CONFIG.BLOG_DESCRIPTION');
    }

    /**
     * @return View|JsonResponse
     */
    public function index(Request $request, CommentRepository $commentRepository, TagRepository $tagRepository)
    {
        $posts = Post::select('posts.id', 'posts.user_id', 'posts.slug', 'posts.title', 'posts.description', 'posts.publishedAt', 'posts.img');

        $searchTitle = '';

        if ($request->title) {
            $posts = $posts->where('title', 'LIKE', "%$request->title%");
            $searchTitle = $request->title;
        }

        $posts = $posts->where('type', PageTypes::BLOG_POST)->with('categories')->with('author')->orderBy('posts.id', 'desc')->paginate($this->paginate);

        return $this->response->render($request->ajax(), [
            'posts' => $posts,
            'tags' => $tagRepository->getTagsByCondition(['showInPost', 1]),
            'categories' => Category::select('name', 'slug')->get(),
            'latestComments' => $commentRepository->getLatestComments(5),
            'searchTitle' => $searchTitle,
            'title' => $this->title,
            'description' => $this->description,
        ], 'blog.index.indexAjax', 'blog.index.index');
    }

    /**
     * @return View|JsonResponse
     */
    public function postsByCategory(
        Request $request,
        string $slug,
        PostRepository $postRepository,
        CommentRepository $commentRepository,
        TagRepository $tagRepository
    ) {
        $category = Category::select('id', 'name')->where('slug', '=', $slug)->firstOrFail();
        $page = (int) $request->input('page') ?? 1;

        return $this->response->render($request->ajax(), [
            'posts' => $postRepository->getPostsByCategory($category->id, $this->paginate, $page),
            'tags' => $tagRepository->getTagsByCondition(['showInPost', 1]),
            'categories' => Category::all(),
            'latestComments' => $commentRepository->getLatestComments(5),
            'slug' => [
                'name' => $category->name,
                'searchTitle' => 'kategori'
            ],
            'title' => $this->title,
            'description' => $this->description
        ], 'blog.index.indexAjax', 'blog.index.index');
    }

    /**
     * @return View|JsonResponse
     */
    public function postsByTag(
        Request $request,
        string $slug,
        PostRepository $postRepository,
        CommentRepository $commentRepository,
        TagRepository $tagRepository
    ) {
        $tagSearch = $tagRepository->getTagBySlug($slug);
        $page = (int) $request->input('page') ?? 1;

        return $this->response->render($request->ajax(), [
            'posts' => $postRepository->getPostsByTagAndType(
                $tagSearch->id,
                PageTypes::BLOG_POST,
                ['posts.id', 'posts.user_id', 'posts.slug', 'posts.title', 'posts.description', 'posts.publishedAt', 'posts.img', 'posts.content'],
                $page,
                true,
                true,
                $this->paginate,
            ),
            'tags' => $tagRepository->getTagsByCondition(['showInPost', 1]),
            'categories' => Category::all(),
            'latestComments' =>  $commentRepository->getLatestComments(5),
            'slug' => [
                'name' => $tagSearch->name,
                'searchTitle' => 'tagu'
            ],
            'title' => $this->title,
            'description' => $this->description,
        ], 'blog.index.indexAjax', 'blog.index.index');
    }

    /**
     * @return View|JsonResponse
     */
    public function singlePost(Request $request, string $slug, PostRepository $postRepository)
    {
        $post = $postRepository->getSinglePost($slug, PageTypes::BLOG_POST, ['*'], true, true, true);

        return $this->response->render($request->ajax(), [
            'post' => $post,
            'title' => $post->title,
            'description' => $post->description
        ], 'blog.singlePost.singlePostAjax', 'blog.singlePost.singlePost');
    }
}

resources/views/admin/post/create.blade.php
@extends('layouts.app')
@section('title', 'Dodawanie posta')
@section('content')
@include('titlePage')
@include('adminMenu')
<article class="container-fluid grey-cont">
    <div class="row">
        <div class="container kolor">
            <form action="{{ route('post.store') }}" method="post" class="form-horizontal" enctype="multipart/form-data">
                @csrf
                @include('admin.post.postForm')
            </form>
        </div>
    </div>
</article>
@endsection

resources/views/admin/post/edit.blade.php
@extends('layouts.app')
@section('title', 'Edycja posta')
@section('content')
@include('titlePage')
@include('adminMenu')
<article class="container-fluid grey-cont">
    <div class="row">
        <div class="container kolor">
            <form action="{{ route('post.update',$post->id) }}" method="post" class="form-horizontal" enctype="multipart/form-data">
                @csrf
                <input name="_method" type="hidden" value="PUT">
                @include('admin.post.postForm')
            </form>
        </div>
    </div>
</article>
@endsection

resources/views/admin/post/postForm.blade.php
<div class="row">
    <div class="form-group">
        <!--    <label class="col-sm-2 control-label text-left" for="content">POST Text:</label>-->
        <div class="col-sm-12">
            <textarea placeholder="text-posta" class="form-control custom-control form-control-special edytor"
                name="content" id="content"
                rows="50">{{ old('content',  isset($post->content) ? $post->content : null) }}</textarea>
        </div>
        <div class="clearfix"></div>
        @if ($errors->has('content'))
        <div class="errormessage invalid-feedback">
            <strong>{{ $errors->first('content') }}</strong>
        </div>
        @endif
        <div id="content_text"></div>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-2 control-label" for="title">Tytuł *</label>
    <div class="col-sm-10">
        <input type="text" name="title" class="contakt100 form-control form-control-special"
            placeholder="tutuł posta .. np jak zrobić..." id="title"
            value="{{ old('title',  isset($post->title) ? $post->title : null) }}">
    </div>
    @if ($errors->has('title'))
    <div class="errormessage invalid-feedback">
        <strong>{{ $errors->first('title') }}</strong>
    </div>
    @endif
    <div id="title_text"></div>

</div>
<div class="form-group">
    <label class="col-sm-2 control-label" for="publishedAt">publishedAt *</label>
    <div class="col-sm-10">
        <input type="text" name="publishedAt" class="contakt100 form-control form-control-special" id="publishedAt"
            value="{{ old('publishedAt',  isset($post->publishedAt) ? $post->publishedAt : null) }}">
    </div>
    @if ($errors->has('publishedAt'))
    <div class="errormessage invalid-feedback">
        <strong>{{ $errors->first('publishedAt') }}</strong>
    </div>
    @endif

</div>
<h1>Dane seo i linki</h1>

<div class="form-group">
    <label class="col-sm-2 control-label" for="headtitle">headtitle *</label>
    <div class="col-sm-10">
        <input type="text" name="headtitle" class="contakt100 form-control form-control-special"
            placeholder="tytuł/headtitle dla sekcji head max 71 znaków" id="headtitle"
            value="{{ old('headtitle',  isset($post->headtitle) ? $post->headtitle : null) }}" maxlength='71'>
    </div>
    @if ($errors->has('headtitle'))
    <div class="errormessage invalid-feedback">
        <strong>{{ $errors->first('headtitle') }}</strong>
    </div>
    @endif
    <div id="headtitle_text"></div>
</div>
<div class="form-group">
    <label class="col-sm-2 control-label" for="keyworks">keyworks *</label>
    <div class="col-sm-10">
        <input type="text" name="keyworks" class="contakt100 form-control form-control-special"
            placeholder="keyworks... max 200 znaków" id="keyworks"
            value="{{ old('keyworks',  isset($post->keyworks) ? $post->keyworks : null) }}" maxlength='200'>
    </div>
    @if ($errors->has('keyworks'))
    <div class="errormessage invalid-feedback">
        <strong>{{ $errors->first('keyworks') }}</strong>
    </div>
    @endif
    <div id="keyworks_text"></div>
</div>

<div class="form-group">
    <label class="col-sm-2 control-label" for="description">description */Krótki opis do 278 znakow posta na
        blogu</label>
    <div class="col-sm-10">
        <textarea maxlength='278' placeholder="Krótki opis ..." class="form-control custom-control form-control-special"
            name="description" id="description"
            rows="10">{{ old('description',  isset($post->description) ? $post->description : null) }}</textarea>
    </div>
    @if ($errors->has('description'))
    <div class="errormessage invalid-feedback">
        <strong>{{ $errors->first('description') }}</strong>
    </div>
    @endif
    <div id="description_text"></div>
</div>
<div class="form-group">
    <div class="col-xs-12">
        <h3><b>Kategorie</b></h3>
        @foreach ($categories as $category)
        <span class="checkbox-choice">
            <input type="checkbox" class="form-check-input" id="cat_{{$category->id}}" value="{{$category->id}}"
                name="categories[]" @if(isset($selectCategories)) @if(is_array($selectCategories) &&
                in_array($category->id, $selectCategories))checked @endif
            @else
            @if(is_array(old('categories')) && in_array($category->id, old('categories')))checked @endif
            @endif
            >
            <label for="cat_{{$category->id}}"><span>x</span> {{$category->name}}</label>
        </span>
        @endforeach

        @if ($errors->has('categories'))
        <div class="errormessage invalid-feedback">
            <strong>{{ $errors->first('categories') }}</strong>
        </div>
        @endif
    </div>
</div>
<div class="form-group">
    <div class="col-xs-12">
        <h3><b>Tagi</b></h3>
        @foreach ($tags as $tag)
        <span class="checkbox-choice">
            <input type="checkbox" class="form-check-input" id="tag_{{$tag->id}}" value="{{$tag->id}}" name="tags[]"
                @if(isset($selectTags)) @if(is_array($selectTags) && in_array($tag->id, $selectTags)) checked @endif
            @else
            @if(is_array(old('tags')) && in_array($tag->id, old('tags'))) checked @endif
            @endif
            >
            <label for="tag_{{$tag->id}}"><span>x</span> {{$tag->name}}</label>
        </span>
        @endforeach
        @if ($errors->has('tags'))
        <div class="errormessage invalid-feedback">
            <strong>{{ $errors->first('tags') }}</strong>
        </div>
        @endif
    </div>
</div>
<div class="form-group">
    <label class="col-sm-2 control-label" for="img">Typ strony</label>
    <div class="col-sm-10">
        <select class="form-control form-control form-control-special" name="type">
            <option value="">-----</option>
            @foreach($types as $typeKey => $type)
            @if( old('type', isset($post->type) ? $post->type : null) == $typeKey)
            <option selected value="{{$typeKey}}">{{$type}}</option>
            @else
            <option value="{{$typeKey}}">{{$type}}</option>
            @endif
            @endforeach
        </select>
    </div>
    @if ($errors->has('type'))
    <div class="errormessage invalid-feedback">
        <strong>{{ $errors->first('type') }}</strong>
    </div>
    @endif
</div>
<div class="form-group">
    <label class="col-sm-2 control-label" for="img">Zdjecie tla posta</label>
    <div class="col-sm-10">
        <input type="text" name="img" class="contakt100 form-control form-control-special" placeholder="adres zdjecia"
            id="img" value="{{ old('img',  isset($post->img) ? $post->img : null) }}" maxlength='255'>
    </div>
    @if ($errors->has('img'))
    <div class="errormessage invalid-feedback">
        <strong>{{ $errors->first('img') }}</strong>
    </div>
    @endif
    <div id="img_text"></div>
</div>
<div class="form-group">
    <label class="btn btn-default btn-file">
        <input name="image_upload_box" type="file" id="image_upload_box" size="40" />
    </label>
    <div clas="showPhoto">
        <img class="img-responsive" src="" alt="" id="showPhoto">
    </div>
</div>
<div class="form-group">
    <div class="col-xs-12">
        <h3>Komentarze</h3>
    </div>
    <div class="col-xs-12">
        <h6>*Zaznaczenie tej opcji umozliwia pokazanie już dodanych komentarzy.</h6>
        <span class="checkbox-choice">
            <input type="checkbox" class="form-check-input" id="show_added_comments" name="show_added_comments" value="1" 
            @if(old('show_added_comments') || (true === old('show_added_comments', $post->show_added_comments ?? null)))
            checked
            @endif
            >
            <label for="show_added_comments"><span>x</span> Włącz pokazywanie komentarzy</label>
        </span>
    </div>
    <div class="col-xs-12">
        <h6>*Zaznaczenie tej opcji pozwala dodawać komentarze.</h6>
        <span class="checkbox-choice">
            <input type="checkbox" class="form-check-input" id="let_add_comments" name="let_add_comments" value="1" 
            @if(old('let_add_comments') || (true === old('let_add_comments', $post->let_add_comments ?? null)))
            checked
            @endif
            >
            <label for="let_add_comments"><span>x</span>Pozwalaj dodawać komentarze</label>
        </span>
    </div>
</div>

<div class="form-group">
    <div class="col-sm-12">
        <button type="submit" class="btn btn-primary btn-lg btn-block pull-left" name="add-post">Zapisz</button>
    </div>
</div>

@section('scripts')
<!-- <script src="//cloud.tinymce.com/stable/tinymce.min.js"></script> -->
<script src="https://cloud.tinymce.com/stable/tinymce.min.js?apiKey=pfir6tw1aejvqvi10svdtwbptl0arnvh4lbkrpg55kumq548">
</script>
<script>
    $(window).on('load', function() {
    tinymce.init({
        selector: '#content',
        height: 700,
        theme: 'modern',
        plugins: [
            'advlist autolink lists link image charmap print preview hr anchor pagebreak',
            'searchreplace wordcount visualblocks visualchars code fullscreen',
            'insertdatetime media nonbreaking save table contextmenu directionality',
            'emoticons template paste textcolor colorpicker textpattern imagetools codesample toc help'
        ],
        toolbar1: 'undo redo | insert | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image',
        toolbar2: 'print preview media | forecolor backcolor emoticons | codesample help',
        image_advtab: true,
        templates: [
            {title: 'Test template 1', content: 'Test 1'},
            {title: 'Test template 2', content: 'Test 2'}
        ],
        content_css: [
            '//fonts.googleapis.com/css?family=Lato:300,300i,400,400i',
            '//www.tinymce.com/css/codepen.min.css'
        ],
    });
});
$.fn.extend({
    limiter: function(limit, elem) {
        try {
            $(this).on("keyup focus", function() {
                //$('body').find(this).on("keyup focus", function() {
                setCount(this, elem);
            });
            function setCount(src, elem) {
                var chars = src.value.length;
                if (chars > limit) {
                    src.value = src.value.substr(0, limit);
                    chars = limit;
                }
                elem.html(limit - chars);
            }
            ;
            setCount($(this)[0], elem);
        } catch (err) {
            console.log(err.message);
        }
    }
});

$(window).on('load', function() {
    $("#title").limiter(100, $("#title_text"));
    $("#description").limiter(278, $("#description_text"));
    $("#keyworks").limiter(200, $("#keyworks_text"));
    $("#headtitle").limiter(71, $("#headtitle_text"));
});
</script>
<style>
    .checkbox-choice input[type="checkbox"] {
        display: none;
    }

    .checkbox-choice span {
        display: none;
    }

    .checkbox-choice label {
        border: 1px solid #177CA4;
        padding: 5px;
        cursor: pointer;
        border-radius: 5px;
    }

    .checkbox-choice input[type="checkbox"]:checked+label {
        background-color: #177CA4;
        color: white;
    }

    .checkbox-choice input[type="checkbox"]:checked+label span {
        display: inline-block;
        color: black;
    }
</style>
@endsection

resources/views/admin/post/show.blade.php
@extends('layouts.app')
@section('title', 'Post')
@section('content')
@include('titlePage')
<article class="container-fluid grey-cont">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="well">
                <div>
                    <label>Url: {{route('blog.single',$post->slug ? $post->slug : '')}}</label>
                    <p><a href="{{route('blog.single',$post->slug ? $post->slug : '')}}">Przejdz do postu</a></p>
                </div>
                <hr>
                <div class="row">
                    <div class="col-sm-6">
                        <h3>Kategorie:</h3>
                        @foreach ($post->categories as $category)
                            <span class="label label-default">{{ $category->name }}</span>
                        @endforeach
                    </div>
                    <div class="col-sm-6 tags">
                        <h3>Tagi</h3>
                        @foreach ($post->tags as $tag)
                            <span class="label label-default">{{ $tag->name }}</span>
                        @endforeach
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-sm-6">
                        <label>Data utworzenia:</label>
                        <p>{{$post->publishedAt}}</p>
                    </div>
                    <div class="col-sm-6">
                        <label>Data ostatniej modyfikacji:</label>
                        <p>{{$post->updatedAt}}</p>
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-sm-6">
                        <a href="{{ route('post.edit', $post->id) }}" class="btn btn-primary btn-block">Edit</a>
                    </div>
                    <div class="col-sm-6">
                        <form method="POST" action="{{ route('post.destroy', $post->id) }}" accept-charset="UTF-8"><input name="_method" type="hidden" value="DELETE">
                            @csrf
                            <input class="btn btn-danger btn-block" type="submit" value="Delete">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <h1>{{ $post->title }}</h1>
            <hr style="height: 2px;background-color: black">
        </div>
        <div class="clearfix"></div>
        <div class="lead">{!! $post->content !!}</div>
    </div>
    <hr style="height: 2px;background-color: black">
    <section id="backend-comments" style="margin-top: 50px;">
        <button id="showHidden" class="btn btn-success">pokaz szczegolowe dane</button>
        <h3>Komentarze <b>({{$post->comments()->count()}})</b></h3>
        <table class="table">
            <thead>
                <tr>
                    <th>id</th>
                    <th>comment_parent</th>
                    <th>Autor</th>
                    <th>Email</th>
                    <th>Komentarz</th>
                    <th class="hiddenData">Ip</th>
                    <th class="hiddenData">Data</th>
                    <th width="70px">Akcja</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($post->comments as $comment)
                <tr @if($comment->deleted_at!=null) {{'style=background-color:red;color:white'}} @endif>
                     <th>{{$comment->id}}</th>
                    <th>{{$comment->comment_parent}}</th>
                    <th>{{$comment->comment_author}}</th>
                    <th>{{$comment->comment_author_email}}</th>
                    <th>{{$comment->comment_content}}</th>
                    <th class="hiddenData" >{{$comment->comment_author_ip}}</th>
                    <th class="hiddenData" >{{$comment->comment_agent}}</th>
                    <th width="70px">
                        <a class="btn btn-primary" href="{{route('comment.edit', $comment->id) }}" onclick="return confirm('Napewno usunąć ?');">edycja</a>
                        <form action="{{ URL::route('comment.destroy', $comment->id) }}" method="POST">
                            <input type="hidden" name="_method" value="DELETE">
                            @csrf
                            <button class="btn btn-danger">usun</button>
                        </form>
                    </th>
                </tr>
                @endforeach
            </tbody>
        </table>
    </section>
</article>
<style>
    .hiddenData{display: none;}
    .block{display: table-cell;}
</style>

<script>
    document.getElementById('showHidden').addEventListener('click', function () {
        var hiddenData = document.querySelectorAll('.hiddenData');
        hiddenData.forEach(function (item) {
            item.classList.toggle('block');
        })
    })
</script>
@endsection