routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\PostController;
use App\Http\Controllers\Admin\PostController as AdminPostController;
use App\Http\Controllers\FastPostController;
use App\Http\Controllers\MainPagesAjaxController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\Contact\ContactController;
use App\Http\Controllers\Admin\TagController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Upload\UploadFilesController;
use App\Http\Controllers\Admin\UserController;

// Auth::routes();
Auth::routes(['register' => false]);
//Route::get('/login', ['as' => 'login', 'uses' => 'Auth\LoginController@showLoginForm']);
//Route::post('/login', ['as' => 'login', 'uses' => 'Auth\LoginController@login']);
//Route::post('/logout', ['as' => 'logout', 'uses' => 'Auth\LoginController@logout']);
//Route::get('password/reset', 'Auth\ResetPasswordController@showResetForm')->name('password.request');
//===============================================================================================
Route::get('/blog', [PostController::class, 'index'])->name('blog');
Route::get('/blog/category/{slug}', [PostController::class, 'postsByCategory'])->name('blogCategory');
Route::get('/blog/tag/{slug}', [PostController::class, 'postsByTag'])->name('blogTag');
Route::get('blog/{slug}', [PostController::class, 'singlePost'])->name('blog.single');

Route::get('fastpost', [FastPostController::class, 'index'])->name('FastPost');
Route::get('fastpost/{slug}', [FastPostController::class, 'singleFastPost'])->name('fastPostSingle');
Route::get('/fastpost/tag/{slug}', [FastPostController::class, 'fastPostsByTag'])->name('FastPostTag');
//===============================================================================================
Route::get('comment/getpostcomments/{postId}/{parentId?}/{offset?}', [CommentController::class, 'getPostComments'])->name('comment.getpostcomments');
Route::resource('comment', CommentController::class)->only('store');
Route::resource('contact', ContactController::class)->only(['index', 'store']);
//===============================================================================================
//===============================================================================================
Route::group(['middleware' => ['role:ROLE_REDACTOR']], function () {
    Route::resource('/admin/post', AdminPostController::class)->only('create', 'store', 'index', 'show', 'edit', 'update', 'destroy');
    Route::resource('/admin/upload-files/get', UploadFilesController::class);
});
//===============================================================================================
Route::group(['middleware' => ['role:ROLE_ADMIN']], function () {
    Route::resource('/admin/categories', CategoryController::class)->only(['index', 'edit', 'update', 'create', 'store']);
    Route::resource('/admin/comment',  CommentController::class)->only(['edit', 'update']);
    Route::resource('/admin/tags', TagController::class)->only(['index', 'edit', 'update', 'create', 'store']);
});
//===============================================================================================
Route::group(['middleware' => ['role:ROLE_SUPER_ADMIN']], function () {
    Route::resource('/admin/categories', CategoryController::class)->only(['destroy']);
    Route::resource('/admin/comment', CommentController::class)->only('destroy');
    Route::resource('/admin/tags', TagController::class)->only(['destroy']);
    Route::resource('/admin/user', UserController::class)->only(['create', 'store', 'index', 'show', 'edit', 'update', 'destroy']);
});
//Route::resource('/adminfastpost', 'Admin\FastPostController', ['as' => 'fastpost','only' => ['index','edit', 'update','create','store','show']]);
Route::get('/', [MainPagesAjaxController::class, 'index'])->name('home');
Route::get('/{any}', [MainPagesAjaxController::class, 'index'])->name('pages')->where('any', '.*');

app/Http/Controllers/Admin/TagController.php
<?php

declare(strict_types=1);

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\TagRequest;
use App\Http\Model\Tag;
use Illuminate\Support\Facades\DB;
use Illuminate\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Support\Str;

class TagController extends Controller
{
    public function index(): View
    {
        return view('admin.tag.index', [
            'tags' => Tag::orderBy('id', 'asc')->get()
        ]);
    }

    public function create(): View
    {
        return view('admin.tag.create');
    }

    public function store(TagRequest $tagRequest, Tag $tag): RedirectResponse
    {
        $tag->createNew($tagRequest);

        return redirect()->route('tags.index')->with('message', 'Dodałem tag');
    }

    public function edit(Tag $tag): View
    {
        return view('admin.tag.edit', [
            'tag' => $tag
        ]);
    }

    public function update(TagRequest $tagRequest, Tag $tag): RedirectResponse
    {
        $tag->update([
            'name' => $tagRequest->name,
            'slug' => Str::slug($tagRequest->name),
            'showInPost' => isset($tagRequest->showInPost) ? 1 : 0,
            'showInFastPost' => isset($tagRequest->showInFastPost) ? 1 : 0,
        ]);

        return back()->with('message', 'Update taga');
    }

    public function destroy(int $id): RedirectResponse
    {
        DB::table('post_tag')->where('tag_id', '=', $id)->delete();
        Tag::where('id', '=', $id)->delete();

        return back()->with('message', 'usunąłem tag i tagi z postow');
    }
}

resources/views/admin/tag/create.blade.php
@extends('layouts.app')
@section('title', 'Nowy tag')
@section('content')
    @include('titlePage')
    @include('adminMenu')
    <article class="container-fluid grey-cont">
        <div class="container kolor">
            <form action="{{ route('tags.store') }}" method="post" class="form-horizontal">
                @csrf
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="name">Nazwa *</label>
                    <div class="col-sm-10">
                        <input type="text" name="name" class="contakt100 form-control form-control-special"
                               placeholder="nazwa tagu" id="name" value="{{ old('name') }}">
                    </div>
                    @if ($errors->has('name'))
                        <div class="errormessage invalid-feedback"><strong>{{ $errors->first('name') }}</strong></div>
                    @endif
                </div>

                <div class="form-group">
                    <div class="col-sm-12">
                        <button type="submit" class="btn btn-primary btn-lg btn-block pull-left" name="add-post">
                            zapisz
                        </button>
                    </div>
                </div>

            </form>
        </div>
    </article>
@endsection
@section('scripts')
@endsection

resources/views/admin/tag/edit.blade.php
@extends('layouts.app')
@section('title', 'Edycja taga')
@section('content')
@include('titlePage')
@include('adminMenu')
<article class="container-fluid grey-cont">
    <div class="container kolor">
        <form action="{{ route('tags.update',$tag->id) }}" method="post" class="form-horizontal" enctype="multipart/form-data">
            @csrf
            <input name="_method" type="hidden" value="PUT">
            <input name="idTag" type="hidden" value="{{$tag->id}}">
            <div class="form-group">
                <label class="col-sm-2 control-label" for="name">Nazwa *</label>
                <div class="col-sm-10">
                    <input type="text" name="name" class="contakt100 form-control form-control-special"  placeholder="tutuł posta .. np jak zrobić..." id="name" value="{{$tag->name}}">
                </div>
                @if ($errors->has('name'))
                <div class="errormessage invalid-feedback"><strong>{{ $errors->first('name') }}</strong></div>
                @endif
            </div>
            <div class="form-group">
                <label for="showInPost">
                    <h3>Pokaz w wyszukiwaniu na blogu</h3>
                    <input type="checkbox" name="showInPost" id="showInPost" value="1" @if ($tag->showInPost==true){{'checked'}}@endif>
                    
                </label>
            </div>
            <div class="form-group">
                <label for="showInFastPost">
                    <h3>Pokaz w wyszukiwaniu w szybkich postach</h3>
                    <input type="checkbox" name="showInFastPost" id="showInFastPost" value="1" @if ($tag->showInFastPost==true){{'checked'}}@endif>
                </label>
            </div>
            <div class="form-group">
                <div class="col-sm-12">
                    <button type="submit" class="btn btn-primary btn-lg btn-block pull-left" name="add-post" >zapisz</button>
                </div>
            </div>
        </form>
    </div>
</article>
@endsection
@section('scripts')
@endsection

resources/views/admin/tag/index.blade.php
@extends('layouts.app')
@section('title', 'Tagi na blogu')
@section('content')
    @include('titlePage')
    @include('adminMenu')

    <article class="container-fluid grey-cont text-center">
        <div class="row">
            <div class="col-md-12">
                <a href="{{ route('tags.create') }}" class="btn btn-lg btn-block btn-primary btn-h1-spacing">Nowy tag</a>
            </div>
            <div class="col-md-12">
                <hr>
            </div>
        </div> <!-- end of .row -->
        <div class="row">
            <div class="table-responsive">
                <table class="table text-center">
                    <thead>
                        <th>id</th>
                        <th>nazwa</th>
                        <th>slug</th>
                        <th>akcja</th>
                    </thead>

                    <tbody>
                    @foreach ($tags as $tag)
                        <tr>
                            <th>{{ $tag->id }}</th>
                            <th>{{ $tag->name }}</th>
                            <th>{{ $tag->slug }}</th>
                            <th>

                                    <form method="POST" action="{{ route('tags.destroy', $tag->id) }}"
                                          accept-charset="UTF-8"><input name="_method" type="hidden" value="DELETE">
                                        @csrf
                                        <input class="btn btn-danger" type="submit" value="Usun" onclick="return confirm('Napewno usunac ? usuniecie spowoduje usunieice tagu oraz tagow w postach');">
                                    </form>

                                    <a href="{{ route('tags.edit', $tag->id) }}" class="btn btn-default btn-sm btn-primary">Edycja</a>

                            </th>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </article>
@endsection
@section('scripts')
@endsection