routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\PostController;
use App\Http\Controllers\Admin\PostController as AdminPostController;
use App\Http\Controllers\FastPostController;
use App\Http\Controllers\MainPagesAjaxController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\Contact\ContactController;
use App\Http\Controllers\Admin\TagController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Upload\UploadFilesController;
use App\Http\Controllers\Admin\UserController;

// Auth::routes();
Auth::routes(['register' => false]);
//Route::get('/login', ['as' => 'login', 'uses' => 'Auth\LoginController@showLoginForm']);
//Route::post('/login', ['as' => 'login', 'uses' => 'Auth\LoginController@login']);
//Route::post('/logout', ['as' => 'logout', 'uses' => 'Auth\LoginController@logout']);
//Route::get('password/reset', 'Auth\ResetPasswordController@showResetForm')->name('password.request');
//===============================================================================================
Route::get('/blog', [PostController::class, 'index'])->name('blog');
Route::get('/blog/category/{slug}', [PostController::class, 'postsByCategory'])->name('blogCategory');
Route::get('/blog/tag/{slug}', [PostController::class, 'postsByTag'])->name('blogTag');
Route::get('blog/{slug}', [PostController::class, 'singlePost'])->name('blog.single');

Route::get('fastpost', [FastPostController::class, 'index'])->name('FastPost');
Route::get('fastpost/{slug}', [FastPostController::class, 'singleFastPost'])->name('fastPostSingle');
Route::get('/fastpost/tag/{slug}', [FastPostController::class, 'fastPostsByTag'])->name('FastPostTag');
//===============================================================================================
Route::get('comment/getpostcomments/{postId}/{parentId?}/{offset?}', [CommentController::class, 'getPostComments'])->name('comment.getpostcomments');
Route::resource('comment', CommentController::class)->only('store');
Route::resource('contact', ContactController::class)->only(['index', 'store']);
//===============================================================================================
//===============================================================================================
Route::group(['middleware' => ['role:ROLE_REDACTOR']], function () {
    Route::resource('/admin/post', AdminPostController::class)->only('create', 'store', 'index', 'show', 'edit', 'update', 'destroy');
    Route::resource('/admin/upload-files/get', UploadFilesController::class);
});
//===============================================================================================
Route::group(['middleware' => ['role:ROLE_ADMIN']], function () {
    Route::resource('/admin/categories', CategoryController::class)->only(['index', 'edit', 'update', 'create', 'store']);
    Route::resource('/admin/comment',  CommentController::class)->only(['edit', 'update']);
    Route::resource('/admin/tags', TagController::class)->only(['index', 'edit', 'update', 'create', 'store']);
});
//===============================================================================================
Route::group(['middleware' => ['role:ROLE_SUPER_ADMIN']], function () {
    Route::resource('/admin/categories', CategoryController::class)->only(['destroy']);
    Route::resource('/admin/comment', CommentController::class)->only('destroy');
    Route::resource('/admin/tags', TagController::class)->only(['destroy']);
    Route::resource('/admin/user', UserController::class)->only(['create', 'store', 'index', 'show', 'edit', 'update', 'destroy']);
});
//Route::resource('/adminfastpost', 'Admin\FastPostController', ['as' => 'fastpost','only' => ['index','edit', 'update','create','store','show']]);
Route::get('/', [MainPagesAjaxController::class, 'index'])->name('home');
Route::get('/{any}', [MainPagesAjaxController::class, 'index'])->name('pages')->where('any', '.*');

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use App\Http\Model\Post;
use Illuminate\Database\Eloquent\Relations\HasMany;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'roles'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'roles' => 'array'
    ];

    public function posts(): HasMany
    {
        return $this->hasMany(Post::class);
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

declare(strict_types=1);

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\User;
use App\Http\Requests\UserRequest;
use App\Domain\User\UserRoles;
use Illuminate\View\View;
use Illuminate\Http\RedirectResponse;

class UserController extends Controller
{
    public function index(): View
    {
        return view('admin.user.index', [
            'users' => User::paginate(10)
        ]);
    }

    public function edit(User $user): View
    {
        return view('admin.user.edit', [
            'user' => $user,
            'userRoles' => UserRoles::getRoleList()
        ]);
    }

    public function update(UserRequest $request, User $user): RedirectResponse
    {
        $userData = $request->all();
        $userData['roles'] = $userData['roles'] ?? [];

        if (isset($userData['password'])) {
            $userData['password'] = bcrypt($userData['password']); //if changing of password docode it to bcrypt
        } else {
            unset($userData['password']); //remove password key if empty
        }

        $user->fill($userData)->save();

        return redirect()->route('user.index')->with('message', 'Zapisałem zmiany');
    }

    public function create(): View
    {
        return view('admin.user.create', [
            'userRoles' => UserRoles::getRoleList()
        ]);
    }

    public function store(UserRequest $tagRequest): RedirectResponse
    {
        $userData = $tagRequest->all();
        $userData['roles'] = $userData['roles'] ?? [];

        if (isset($userData['password'])) {
            $userData['password'] = bcrypt($userData['password']); //if changing of password docode it to bcrypt
        } else {
            unset($userData['password']); //remove password key if empty
        }
        $user = new User();
        $user->fill($userData)->save();

        return redirect()->route('user.index')->with('message', 'Zapisałem nowego typa');
    }
}

resources/views/admin/user/create.blade.php
@extends('layouts.app')
@section('title', 'Edycja danych użytkownika')
@section('content')
@include('titlePage')
@include('adminMenu')
<article class="container-fluid grey-cont">
    <div class="row">
        <div class="col-md-12">
            <a href="{{ route('user.create') }}" class="btn btn-lg btn-block btn-primary btn-h1-spacing">Nowy nowego usera</a>
        </div>
        <div class="col-md-12">
            <hr>
        </div>
    </div> <!-- end of .row -->
    <div class="row">	
        <div class="container kolor">
            <form action="{{ route('user.store') }}" method="post" class="form-horizontal" enctype="multipart/form-data">
                @csrf
                @include('admin.user.userForm')
            </form>
        </div>
    </div>	
</article>
@endsection
@section('scripts')
@endsection

resources/views/admin/user/edit.blade.php
@extends('layouts.app')
@section('title', 'Edycja danych użytkownika')
@section('content')
@include('titlePage')
@include('adminMenu')
<article class="container-fluid grey-cont">
    <div class="row">
        <div class="col-md-12">
            <a href="{{ route('user.create') }}" class="btn btn-lg btn-block btn-primary btn-h1-spacing">Nowy nowego usera</a>
        </div>
        <div class="col-md-12">
            <hr>
        </div>
    </div> <!-- end of .row -->



    <div class="row">	
		<div class="container kolor">
		<form action="{{ route('user.update',$user->id) }}" method="post" class="form-horizontal" enctype="multipart/form-data">
			@csrf
			<input name="_method" type="hidden" value="PUT">
			@include('admin.user.userForm')
		</form>
	</div>

    </div>	

	











</article>
@endsection
@section('scripts')
@endsection

resources/views/admin/user/index.blade.php
@extends('layouts.app')
@section('title', 'Nowa Kategoria')
@section('content')
@include('titlePage')
@include('adminMenu')
<article class="container-fluid grey-cont">
    <div class="row">
        <div class="col-md-12">
            <a href="{{ route('user.create') }}" class="btn btn-lg btn-block btn-primary btn-h1-spacing">Nowy post</a>
        </div>
        <div class="col-md-12">
            <hr>
        </div>
    </div> <!-- end of .row -->
    <div class="row">
        <div class="col-md-12">
            <table class="table">
                <thead>
                <th>id</th>
                <th>imie</th>
                <th>email</th>
                <th>Data utworzenia</th>
                <th>Data ostatniej edycji</th>
                <th>Role</th>
                <th></th>
                </thead>
                <tbody>
                    @foreach ($users as $user)
                    <tr>
                        <th>{{ $user->id }}</th>
                        <td>{{ $user->name }}</td>
                        <td>{{ $user->email }}</td>
                        <td>{{ $user->created_at }}</td>
                        <td>{{ $user->updated_at }}</td>
                        <td>
                            {{implode(' ',$user->roles)}}
                        </td>
                        <td><a href="{{ route('user.show', $user->id) }}" class="btn btn-default btn-sm">Podgląd</a> <a href="{{ route('user.edit', $user->id) }}" class="btn btn-default btn-sm btn-primary">Edycja</a></td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
            <div class="text-center">
                {!! $users->links(); !!}
            </div>
        </div>
    </div>
</article>
@endsection
@section('scripts')
@endsection

resources/views/admin/user/userForm.blade.php
<div class="form-group">
    <label class="col-sm-2 control-label" for="name">Imię *</label>
    <div class="col-sm-10">
        <input type="text" name="name" class="contakt100 form-control form-control-special"  placeholder="imię i nazwisko" id="name" value="{{ old('name',  isset($user->name) ? $user->name : null) }}">
    </div>
    @if ($errors->has('name'))
    <div class="errormessage invalid-feedback">
        <strong>{{ $errors->first('name') }}</strong>
    </div>
    @endif
    <div id="name_text"></div>
</div>
<div class="form-group">
    <label class="col-sm-2 control-label" for="email">Email *</label>
    <div class="col-sm-10">
        <input type="text" name="email" class="contakt100 form-control form-control-special"  placeholder="email ziomka" id="email" value="{{ old('email',  isset($user->email) ? $user->email : null) }}">
    </div>
    @if ($errors->has('email'))
    <div class="errormessage invalid-feedback">
        <strong>{{ $errors->first('email') }}</strong>
    </div>
    @endif
    <div id="name_text"></div>
</div>
<div class="form-group">
    <label class="col-sm-2 control-label" for="password">password *</label>
    <div class="col-sm-10">
        <input type="password" name="password" class="contakt100 form-control form-control-special"  placeholder="hasło" id="password" value="">
    </div>
    @if ($errors->has('password'))
    <div class="errormessage invalid-feedback">
        <strong>{{ $errors->first('password') }}</strong>
    </div>
    @endif
    <div id="name_text"></div>
</div>
<div class="form-group">
    <label class="col-sm-2 control-label" for="password_confirmation">Powtórz hasło *</label>
    <div class="col-sm-10">
        <input type="password" name="password_confirmation" class="contakt100 form-control form-control-special"  placeholder="powtorz haslo" id="password_confirmation" value="">
    </div>
    @if ($errors->has('password_confirmation'))
    <div class="errormessage invalid-feedback">
        <strong>{{ $errors->first('password_confirmation') }}</strong>
    </div>
    @endif
    <div id="name_text"></div>
</div>
<div class="form-group">
    <h3><b>Role użytkownika</b></h3>

    @foreach ($userRoles as $key => $role)
    <span class="checkbox-choice">
        <input type="checkbox" class="form-check-input" id="cat_{{$key}}" value="{{$key}}" name="roles[]"
               @if(isset($user->roles))
               @if(is_array($user->roles) && in_array($key, $user->roles))checked @endif
               @else
               @if(is_array(old('roles')) && in_array($key, old('roles')))checked @endif
               @endif
               >
               <label for="cat_{{$key}}"><span>x</span> {{$role}}</label>
    </span>
    @endforeach

</div>
<div class="form-group">
    <div class="col-sm-12">
        <button type="submit" class="btn btn-primary btn-lg btn-block pull-left" name="add-post" >zapisz</button>
    </div>
</div>
<style>
    .checkbox-choice input[type="checkbox"] {
        display: none;
    }
    .checkbox-choice span {
        display: none;
    }
    .checkbox-choice label {
        border: 1px solid #900000;padding: 5px; cursor: pointer;border-radius: 5px;
    }
    .checkbox-choice input[type="checkbox"]:checked+label {
        background-color:#900000;color: white;
    }
    .checkbox-choice input[type="checkbox"]:checked+label span {
        display: inline-block;color: white;
    }
</style>